version: '3'

services:
  mysql:
    image: mysql:debian
    container_name: converter_db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=converter_db
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
  
  converter:
    image: roretar/back-end-converter:puchero 
    container_name: converter_api
    ports:
      - 5000:5000
    environment:
      - CONVERTER_HOST_ALL=0.0.0.0
      - CONVERTER_HOST=192.168.56.10
      - DB_HOST=172.17.0.1
    depends_on:
      - mysql
    restart: always

  web_converter:
    image: roretar/front-end-converter:bandeja_paisa
    container_name: front_end_converter
    ports:
      - 5017:5017
    depends_on:
      - converter
    restart: always
  
  mongo:
    image: mongo:latest
    container_name: machine_db
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    restart: always
    command: ['--auth']

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - 8081:8081
    depends_on:
      - mongo

  machine-learning:
    image: telmarf/machine-learning:anticucho
    container_name: machine_servece
    volumes:
      - machine_volume:/root/.deepface/weights
    environment:
      - URI='mongodb://root:123@mongo:27017'
    ports:
      - 5001:5001
    depends_on:
      - mongo
    restart: always
  
  front_end_machine:
    image: telmarf/front_machine:cuchuco
    container_name: front_machi
    environment:
      - URL=http://172.17.0.1:5001
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - machine-learning
  
volumes:
  mongo_volume: 
    external: false
  machine_volume:
    external: false
  