# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
echo "I like Vagrant my new love"
echo "I miss windows"
date > /home/vagrant_provisioned_at
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |roger|
    roger.memory = "1024"
  end
  
  config.vm.provision :docker
  config.vm.provision :shell, path: "ssh/bootstrap.sh"
  config.vm.provision :file, source: "file.txt", destination: "file1.txt"
  config.vm.provision :file, source: "t1", destination: "r1"
  config.vm.provision "shell", inline: "echo Hi Class!"
  config.vm.define "server-roger-1" do |dockerserver|
    dockerserver.vm.network "private_network", ip: '192.168.56.43'
    dockerserver.vm.hostname = 'dockerserverhostroger'
    dockerserver.vm.provision "shell", inline: "echo Hi Class2"
    dockerserver.vm.provision "shell", inline: $script
    dockerserver.vm.provision "shell" do |s|
      s.inline = "echo $1"
      s.args = ["AT", "Class!"]
    end
    dockerserver.vm.provision "docker" do |d|
      d.run "hello-world"
    end
  end
end
