# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |roger|
    roger.memory = "2048"
  end
  config.vm.provision :docker
  
  config.vm.define "server-roger-1" do |ds|
    ds.vm.network "private_network", ip: '192.168.56.43'
    ds.vm.hostname = 'dshostroger'
    ds.vm.provision :file, source:"../docker/docker-compose.yaml", destination:"docker-compose.yaml"
    ds.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yaml", run:"always"
    ds.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock && sudo chmod 777 /usr/bin/docker"
  end
end
