version: '3.5'

services:
  jenkins_server:
    image: jenkinsci/blueocean
    container_name: jenkins_server
    restart: always
    ports:
      - "8081:8080"
      - "5000:50000"
    volumes:
      - jenkins_server:/var/jenkins_home

volumes:
  jenkins_server:
    name: jenkins_server