version: '3.5'

services:
  jenkins_server:
    image: jenkins/jenkins:2.393
    container_name: jenkins_server
    restart: always
    ports:
      - "8081:8080"
      - "5000:50000"
    volumes:
      - jenkins_server:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

volumes:
  jenkins_server:
    name: jenkins_server